-d D:\Gowin_work\TangNano-4K-example-skc\key_blink\impl\gwsynthesis\key_blink.vg
-p GW1NSR-4C-QFN48P-6
-pn GW1NSR-LV4CQN48PC6/I5
-cst D:\Gowin_work\TangNano-4K-example-skc\key_blink\src\key_blink.cst
-cfg D:\Gowin_work\TangNano-4K-example-skc\key_blink\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
